"""Add player fields to Team model

Revision ID: 8d79e0f166a8
Revises: 
Create Date: 2025-02-06 11:41:55.030060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d79e0f166a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('player2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('player3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('player4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('player5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('captain', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('captain')
        batch_op.drop_column('player5')
        batch_op.drop_column('player4')
        batch_op.drop_column('player3')
        batch_op.drop_column('player2')
        batch_op.drop_column('player1')

    # ### end Alembic commands ###
